- name: Install bind9                                                                                                                                                                              
  apt:
    name: "bind9"
    state: present

- name: Add named conf
  blockinfile:
    path: /etc/bind/named.conf.default-zones
    marker: "// {mark} ANSIBLE MANAGED BLOCK"
    block: |
      zone "m61-magedu.com" {
          type slave;
          file "/var/cache/bind/db.m61-magedu.com";
          masters { {{ hostvars['dns_master']['ansible_host'] }}; };
      };

- name: rndc reload
  shell: rndc reload
