- name: Install keepalived
  apt:
    name: keepalived
    state: present

- name: Create keepalived config
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf

- name: restart and enable keepalived
  service:
    name: keepalived
    state: restarted
    enabled: true
